name: On push

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
        CI: true

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install
    - name: Check format
      run: |
        npm run fmt
    - name: Compile solidity contracts
      run: |
        npm run compile-contracts
    - name: Run tests
      run: |
        npm run test