dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - "8"
  - "10"
  - "12"

cache:
  directories:
    - node_modules

jobs:
  fast_finish: true
  include:
    - stage: tests
      name: "Linter"
      script: npm run fmt

    - stage: tests
      name: "Unit tests"
      script: npm run test
